/*
 * Builds tests/test_project.pcbr.js — the demo project opened on first start — from tests/test_project.pcbr.
 * A page opened from file:// cannot fetch() files but can load scripts, so the .pcbr ships as base64 in a script.
 * Run after changing test_project.pcbr:   node tests/make_demo.js
 */
const fs = require('fs'), path = require('path');
const src = path.join(__dirname, 'test_project.pcbr'), out = src + '.js';
fs.writeFileSync(out, '/* generated by tests/make_demo.js from test_project.pcbr — do not edit */\n' +
  'window.PCBR_DEMO="' + fs.readFileSync(src).toString('base64') + '";\n');
console.log(path.relative(process.cwd(), out), (fs.statSync(out).size / 1048576).toFixed(1) + ' MB');
